name: Hexo Auto Deploy

on:
  push:
    branches:
      - main # 确保这里是你源码仓库的主分支名

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          submodules: 'false' # 自动拉取 themes 里的主题插件

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Deploy
        env:
          # 在源码仓库 Settings -> Secrets -> Actions 里添加这个 Token
          GH_TOKEN: ${{ secrets.HEXO_DEPLOY_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # 这一步很关键：它会临时修改配置，让 Hexo 有权推送到你的静态仓库
          # 请将下方 [USER] 替换为你的用户名
          sed -i "s|repo:.*|repo: repo: https://${GH_TOKEN}@github.com/klklkl10086/klklkl10086.github.io.git" _config.yml
          
          npx hexo clean
          npx hexo deploy